# Generated by Django 2.0.1 on 2018-02-02 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modir', '0001_initial'),
        ('karbar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MadadjooRegistrationRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karbar.Request')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('fatherName', models.CharField(blank=True, max_length=20)),
                ('sex', models.IntegerField(choices=[(1, 'آقا'), (0, 'خانم')])),
                ('NationalCode', models.CharField(blank=True, max_length=11)),
                ('phoneNumber', models.CharField(blank=True, max_length=12)),
                ('city', models.CharField(blank=True, max_length=20, null=True)),
                ('bankAcount', models.CharField(blank=True, max_length=20)),
                ('grade', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('state', models.IntegerField(choices=[(0, 'نیازمند'), (2, 'یتیم'), (1, 'مستعد')])),
                ('healthStatus', models.IntegerField(choices=[(0, 'سالم'), (1, 'بیمار')], default=0)),
                ('disease', models.CharField(blank=True, max_length=30)),
                ('educationalStatus', models.CharField(blank=True, max_length=30)),
                ('briefDescription', models.TextField(blank=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
            ],
            bases=('karbar.request',),
        ),
        migrations.CreateModel(
            name='Madadkar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NationalCode', models.CharField(max_length=11)),
                ('firstName', models.CharField(blank=True, max_length=20, null=True)),
                ('lastName', models.CharField(blank=True, max_length=20, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('education', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('dateOfEmployeement', models.DateField(blank=True, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=12, null=True)),
                ('karbar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='karbar.Karbar')),
            ],
        ),
        migrations.CreateModel(
            name='MadadkarChangeProfileRequest',
            fields=[
                ('changeprofilerequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karbar.ChangeProfileRequest')),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('education', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('dateOfEmployeement', models.DateField(blank=True, null=True)),
            ],
            bases=('karbar.changeprofilerequest',),
        ),
        migrations.CreateModel(
            name='Warning',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karbar.Notification')),
                ('activity', models.CharField(max_length=20)),
                ('madadkar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madadkar.Madadkar')),
                ('modir', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modir.Modir')),
            ],
            bases=('karbar.notification',),
        ),
        migrations.AddField(
            model_name='madadjooregistrationrequest',
            name='madadkar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='madadkar.Madadkar'),
        ),
        migrations.AddField(
            model_name='madadjooregistrationrequest',
            name='modir',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modir.Modir'),
        ),
    ]
