# Generated by Django 2.0.1 on 2018-02-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadkar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madadjooregistrationrequest',
            name='healthStatus',
            field=models.IntegerField(choices=[(0, 'سالم'), (1, 'بیمار')], default=0),
        ),
        migrations.AlterField(
            model_name='madadjooregistrationrequest',
            name='state',
            field=models.IntegerField(choices=[(1, 'مستعد'), (0, 'نیازمند'), (2, 'یتیم')]),
        ),
    ]
