# Generated by Django 2.0.1 on 2018-02-02 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('karbar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NationalCode', models.CharField(max_length=11)),
                ('firstName', models.CharField(blank=True, max_length=20, null=True)),
                ('lastName', models.CharField(blank=True, max_length=20, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=12, null=True)),
                ('birthDate', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=20)),
                ('education', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('dateOfEmployeement', models.DateField(blank=True, null=True)),
                ('savingAmountOfSystem', models.PositiveIntegerField()),
                ('karbar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='karbar.Karbar')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karbar.Notification')),
                ('modir', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modir.Modir')),
                ('receivers', models.ManyToManyField(related_name='reciverKarbar', to='karbar.Karbar')),
            ],
            bases=('karbar.notification',),
        ),
    ]
