# Generated by Django 2.0.1 on 2018-02-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadjoo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madadjoo',
            name='healthStatus',
            field=models.IntegerField(choices=[(0, 'سالم'), (1, 'بیمار')], default=0),
        ),
        migrations.AlterField(
            model_name='madadjoo',
            name='state',
            field=models.IntegerField(choices=[(1, 'مستعد'), (0, 'نیازمند'), (2, 'یتیم')]),
        ),
        migrations.AlterField(
            model_name='madadjoochangeprofilerequest',
            name='healthStatus',
            field=models.IntegerField(blank=True, choices=[(0, 'سالم'), (1, 'بیمار')], null=True),
        ),
        migrations.AlterField(
            model_name='madadjoochangeprofilerequest',
            name='state',
            field=models.IntegerField(blank=True, choices=[(1, 'مستعد'), (0, 'نیازمند'), (2, 'یتیم')], null=True),
        ),
        migrations.AlterField(
            model_name='need',
            name='type',
            field=models.IntegerField(choices=[(0, 'ماهانه'), (1, 'هفتگی'), (2, 'یکباره')]),
        ),
    ]
