# Generated by Django 2.0.1 on 2018-02-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madadjoo', '0002_auto_20180202_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='madadjoo',
            name='healthStatus',
            field=models.IntegerField(choices=[(1, 'بیمار'), (0, 'سالم')], default=0),
        ),
        migrations.AlterField(
            model_name='madadjoo',
            name='state',
            field=models.IntegerField(choices=[(0, 'نیازمند'), (1, 'مستعد'), (2, 'یتیم')]),
        ),
        migrations.AlterField(
            model_name='madadjoochangeprofilerequest',
            name='healthStatus',
            field=models.IntegerField(blank=True, choices=[(1, 'بیمار'), (0, 'سالم')], null=True),
        ),
        migrations.AlterField(
            model_name='madadjoochangeprofilerequest',
            name='state',
            field=models.IntegerField(blank=True, choices=[(0, 'نیازمند'), (1, 'مستعد'), (2, 'یتیم')], null=True),
        ),
    ]
