# Generated by Django 2.0.1 on 2018-02-02 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modir', '0001_initial'),
        ('madadjoo', '0001_initial'),
        ('madadkar', '0001_initial'),
        ('karbar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hamyar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(blank=True, max_length=12, null=True)),
                ('karbar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='karbar.Karbar')),
            ],
        ),
        migrations.CreateModel(
            name='HamyarChangeProfileRequest',
            fields=[
                ('changeprofilerequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karbar.ChangeProfileRequest')),
            ],
            bases=('karbar.changeprofilerequest',),
        ),
        migrations.CreateModel(
            name='MeetTheMadadjooRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karbar.Request')),
                ('hamyar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hamyar.Hamyar')),
                ('madadjoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madadjoo.Madadjoo')),
                ('modir', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='modir.Modir')),
            ],
            bases=('karbar.request',),
        ),
        migrations.CreateModel(
            name='SendNonCashAidRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karbar.Request')),
                ('hamyar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hamyar.Hamyar')),
                ('madadjoo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madadjoo.Madadjoo')),
                ('madadkar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='madadkar.Madadkar')),
            ],
            bases=('karbar.request',),
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hamyar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hamyar.Hamyar')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madadjoo.Payment')),
            ],
        ),
    ]
