# Generated by Django 2.0.1 on 2018-02-02 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import karbar.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Karbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=karbar.models.get_image_path)),
                ('user_type', models.IntegerField(choices=[(1, 'madadjoo'), (2, 'hamyar'), (3, 'modir'), (0, 'madadkar')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=1000)),
                ('date', models.DateField()),
                ('receiveMessageStatus', models.IntegerField(choices=[(0, 'دریافت شد'), (1, 'دریافت نشد')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karbar.Notification')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='karbar.Karbar')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sender', to='karbar.Karbar')),
            ],
            bases=('karbar.notification',),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('notification_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karbar.Notification')),
            ],
            bases=('karbar.notification',),
        ),
        migrations.CreateModel(
            name='ChangeProfileRequest',
            fields=[
                ('request_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='karbar.Request')),
                ('firstName', models.CharField(blank=True, max_length=20)),
                ('lastName', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(blank=True, max_length=30)),
                ('fatherName', models.CharField(blank=True, max_length=20)),
                ('sex', models.IntegerField(blank=True, choices=[(1, 'آقا'), (0, 'خانم')], null=True)),
                ('NationalCode', models.CharField(blank=True, max_length=11)),
                ('phoneNumber', models.CharField(blank=True, max_length=12)),
                ('karbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='karbar.Karbar')),
            ],
            bases=('karbar.request',),
        ),
    ]
