# Generated by Django 2.0.1 on 2018-02-02 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karbar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karbar',
            name='user_type',
            field=models.IntegerField(choices=[(0, 'madadkar'), (1, 'madadjoo'), (3, 'modir'), (2, 'hamyar')], null=True),
        ),
    ]
