# Generated by Django 2.0.1 on 2018-02-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karbar', '0002_auto_20180202_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karbar',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'madadjoo'), (0, 'madadkar'), (2, 'hamyar'), (3, 'modir')], null=True),
        ),
    ]
